name: Theme Check

on:
  pull_request:
    paths:
      - "layout/**"
      - "sections/**"
      - "snippets/**"
      - "templates/**"
      - "assets/**"
      - ".theme-check.yml"
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - run: gem install theme-check --no-document
      - run: theme-check --fail-level=error
